url: "http://hullmanlab.northwestern.edu/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/" # the subpath of your site, e.g. /blog
title: "Epistemic Interactions Lab" # the name of your site, e.g. ACME Corp.
